### ISSUE TITLE
[Bug] CloudCost BigQueryQuerier: Query: error reading query results

### ISSUE THREAD

**Issue by dwilliams782** [kubecost/features-bugs#120]
### Kubecost Version

2.3.5

### Kubernetes Version

1.29

### Kubernetes Platform

GKE

### Description

I've set up the GCP cloud cost integration pointing at a BQ dataset. The integration looks to be successful, but the logs have some errors:

```
2024-09-13T14:17:59.677240475Z ERR CloudCost[<billing-dataset>]: ingestor: build failed for window [2024-06-14T00:00:00+0000, 2024-06-21T00:00:00+0000): error querying: BigQueryQuerier: Query: error reading query results: googleapi: Error 400: Unrecognized name: resource at [2:202], invalidQuery

2024-09-13T14:17:59.677324095Z INF CloudCost[<billing-dataset>]: ingestor: build[ooeaS]:  [2024-06-14T00:00:00+0000, 2024-06-21T00:00:00+0000) in 2.404522446s

2024-09-13T14:17:59.677357045Z INF CloudCost[<billing-dataset>]: ingestor: build[ooeaS]: completed in 43.021002556s
```

The status says connected but it is unclear if anything is actually happening:

![image](https://github.com/user-attachments/assets/f4555a39-c78a-49d6-b5c3-d70e05e08f8e)

### Steps to reproduce

1. Enable GCP billing export
2. Watch the logs

### Expected behavior

No errors

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwilliams782** [comment]
I found a failed query in the project history:

```
SELECT TIMESTAMP_TRUNC(usage_start_time, day) as usage_date, billing_account_id as billing_id, project.id as project_id, service.description as service, sku.description as description, resource.name as resource, resource.global_name as global_resource, TO_JSON_STRING(labels) as labels, SUM(cost) as cost, SUM(cost_at_list) as list_cost, ARRAY_CONCAT_AGG(credits) as credits
		FROM  `<billing-dataset>` bd 
		WHERE DATE(_PARTITIONTIME) >= "2024-06-14" AND DATE(_PARTITIONTIME) < "2024-06-23" AND usage_start_time >= "2024-06-14" AND usage_start_time < "2024-06-21"
		GROUP BY usage_date, billing_id, project_id, service, description, labels, resource, global_resource
```

resource doesn't exist in the schema:

```
gcloud alpha bq tables describe <table> --dataset <dataset>  --project <project>
creationTime: '1617720458265'
etag: NHlpcI7yka6ayl9e4BO8gA==
id: <project.dataset.table>
kind: bigquery#table
lastModifiedTime: '1726232578797'
location: europe-west2
numActiveLogicalBytes: '45459238327'
numActivePhysicalBytes: '1713834209'
numBytes: '236025213342'
numCurrentPhysicalBytes: '4927435497'
numLongTermBytes: '190565975015'
numLongTermLogicalBytes: '190565975015'
numLongTermPhysicalBytes: '3792273739'
numPartitions: '1256'
numRows: '282904675'
numTimeTravelPhysicalBytes: '578672451'
numTotalLogicalBytes: '236025213342'
numTotalPhysicalBytes: '5506107948'
schema:
  fields:
  - description: ''
    mode: NULLABLE
    name: billing_account_id
    type: STRING
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: id
      type: STRING
    - description: ''
      mode: NULLABLE
      name: description
      type: STRING
    mode: NULLABLE
    name: service
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: id
      type: STRING
    - description: ''
      mode: NULLABLE
      name: description
      type: STRING
    mode: NULLABLE
    name: sku
    type: RECORD
  - description: ''
    mode: NULLABLE
    name: usage_start_time
    type: TIMESTAMP
  - description: ''
    mode: NULLABLE
    name: usage_end_time
    type: TIMESTAMP
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: id
      type: STRING
    - description: ''
      mode: NULLABLE
      name: number
      type: STRING
    - description: ''
      mode: NULLABLE
      name: name
      type: STRING
    - description: ''
      fields:
      - description: ''
        mode: NULLABLE
        name: key
        type: STRING
      - description: ''
        mode: NULLABLE
        name: value
        type: STRING
      mode: REPEATED
      name: labels
      type: RECORD
    - description: ''
      mode: NULLABLE
      name: ancestry_numbers
      type: STRING
    - description: ''
      fields:
      - description: ''
        mode: NULLABLE
        name: resource_name
        type: STRING
      - description: ''
        mode: NULLABLE
        name: display_name
        type: STRING
      mode: REPEATED
      name: ancestors
      type: RECORD
    mode: NULLABLE
    name: project
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: key
      type: STRING
    - description: ''
      mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: labels
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: key
      type: STRING
    - description: ''
      mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: system_labels
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: location
      type: STRING
    - description: ''
      mode: NULLABLE
      name: country
      type: STRING
    - description: ''
      mode: NULLABLE
      name: region
      type: STRING
    - description: ''
      mode: NULLABLE
      name: zone
      type: STRING
    mode: NULLABLE
    name: location
    type: RECORD
  - description: ''
    mode: NULLABLE
    name: export_time
    type: TIMESTAMP
  - description: ''
    mode: NULLABLE
    name: cost
    type: FLOAT
  - description: ''
    mode: NULLABLE
    name: currency
    type: STRING
  - description: ''
    mode: NULLABLE
    name: currency_conversion_rate
    type: FLOAT
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: amount
      type: FLOAT
    - description: ''
      mode: NULLABLE
      name: unit
      type: STRING
    - description: ''
      mode: NULLABLE
      name: amount_in_pricing_units
      type: FLOAT
    - description: ''
      mode: NULLABLE
      name: pricing_unit
      type: STRING
    mode: NULLABLE
    name: usage
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: name
      type: STRING
    - description: ''
      mode: NULLABLE
      name: amount
      type: FLOAT
    - description: ''
      mode: NULLABLE
      name: full_name
      type: STRING
    - description: ''
      mode: NULLABLE
      name: id
      type: STRING
    - description: ''
      mode: NULLABLE
      name: type
      type: STRING
    mode: REPEATED
    name: credits
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: month
      type: STRING
    mode: NULLABLE
    name: invoice
    type: RECORD
  - description: ''
    mode: NULLABLE
    name: cost_type
    type: STRING
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: id
      type: STRING
    - description: ''
      mode: NULLABLE
      name: description
      type: STRING
    - description: ''
      mode: NULLABLE
      name: mode
      type: STRING
    - description: ''
      mode: NULLABLE
      name: type
      type: STRING
    mode: NULLABLE
    name: adjustment_info
    type: RECORD
  - description: ''
    fields:
    - description: ''
      mode: NULLABLE
      name: key
      type: STRING
    - description: ''
      mode: NULLABLE
      name: value
      type: STRING
    - description: ''
      mode: NULLABLE
      name: inherited
      type: BOOLEAN
    - description: ''
      mode: NULLABLE
      name: namespace
      type: STRING
    mode: REPEATED
    name: tags
    type: RECORD
  - mode: NULLABLE
    name: cost_at_list
    type: FLOAT
  - mode: NULLABLE
    name: transaction_type
    type: STRING
  - mode: NULLABLE
    name: seller_name
    type: STRING
selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/<project>/datasets/<dataset>/tables/<table>
tableReference:
  datasetId:<dataset>
  projectId: <project>
  tableId: gcp_billing_export_v1_01B5B8_FBF467_D508C3
timePartitioning:
  type: DAY
type: TABLE
```
