### ISSUE TITLE
[Bug] network monitoring is empty

### ISSUE THREAD

**Issue by anthosz** [kubecost/features-bugs#83]
### Kubecost Version

2.2.2

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Network monitoring is empty

Helm values:
```
global:
  grafana:
    enabled: false
    proxy: false
  prometheus:
    enabled: false
    fqdn: http://prom-stack-prometheus.monitoring.svc:9090
kubecostModel:
  containerStatsEnabled: false
  warmCache: true
networkCosts:
  config:
    services:
      amazon-web-services: true
      azure-cloud-services: false
      google-cloud-services: false
  enabled: true
  prometheusScrape: true
  trafficLogging: true
prometheus:
  enabled: false
  nodeExporter:
    enabled: false
serviceMonitor:
  enabled: true
  networkCosts:
    enabled: true
```

### Steps to reproduce

1. Install the helm chart with theses values
2. Wait few hours
3. I can see well the cost of network by hour but the network monitoring dashboard is empty

If I check prometheus: container_network_transmit_bytes_total is well present but I have the feeling some other metrics are needed. Do you have the full list of needed metrics to be able to use the network monitoring dashboard?

### Expected behavior

Have something in the monitoring

### Screenshots

![image](https://github.com/kubecost/features-bugs/assets/14294064/d70357d0-9597-4f08-ada3-b41d0cf84587)

### Logs

```Shell
NC
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.
