### ISSUE TITLE
[Bug] cloud integration - spot datafeed - no datas

### ISSUE THREAD

**Issue by anthosz** [kubecost/features-bugs#84]
### Kubecost Version

2.2.2

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

AWS was configured to have spot datas but unable to found where I can find these datas in kubecost.

The only thing that I found is that kubecost_node_is_spot is well present with the value 1 when it's a spot instance.

Helm values:
```
...
kubecostProductConfigs:
 projectID: "XXXX"
 awsSpotDataBucket: XXXX
 awsSpotDataRegion: XXXX
 spotLabel: karpenter.sh/capacity-type
 spotLabelValue: spot                                                                                      
...
```

### Steps to reproduce

1. Adding datafeed subscription on EC2
2. Push all the datas on a specific bucket with correct policy for the role
3. Assign role to kubecost

### Expected behavior

Found somewhere this feature to confirm that all is ok:
https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances#no-spot-instances-detected

I cannot found any feature that confirm that spot data feed are well get.

All is ok about Athena datas.

### Screenshots

Only found datas cloud integrations in full diagnostics that is empty:
![image](https://github.com/kubecost/features-bugs/assets/14294064/5b8e515c-2912-4e41-a4e1-ec69f1750c32)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.
