### ISSUE TITLE
[Feature] Allow manage collections through values.yaml

### ISSUE THREAD

**Issue by Hronom** [kubecost/features-bugs#89]
### Problem Statement

We wanna have possibility to manage collections in programmatic way through `values.yaml` as it done with AWS integration. There nos such possibility right now.

### Solution Description

Ideally if `collections.json` can be mounted from external config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  collections.json: |
    {
      "key1": "value1",
      "key2": "value2",
      ...
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image
        volumeMounts:
        - name: config-volume
          mountPath: /path/to/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: my-config
```

This helps to template this json using helm.

### Alternatives

Also it will be even cooler if we can manage it through custom CDR files in Kubernetes. Some controller will run and track whenever `Kind: collection` created it will update collection in Kubecost UI.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
